[package]
name = "minimist"
version = "0.1.0"
edition = "2024"
description = "Transparent, ergonomic, no-dependencies arg processing."
license = "MIT OR Apache-2.0"
readme = "README.md"
documentation = "https://docs.rs/minimist"
repository = "https://github.com/neonphog/minimist"
categories = ["command-line-interface"]
keywords = [
  "argument",
  "cli",
  "arg",
  "parser",
  "parse"
]

[dependencies]
